### ISSUE TITLE
Cannot read property 'job' of undefined

### ISSUE THREAD

**Issue by nickpetrovic** [dave-hagedorn/jenkins-runner#1]
I'm having trouble getting this plugin to work. I _think_ its having trouble connecting to my Jenkins instance.

I'm running Jenkins locally via Docker. It is accessible on port 80 via the browser and I checked via curl to make sure I wasn't missing something. Authentication is disabled too.

I also have a test job named the same as the job in my VSCode settings.

**VSCode**
<img width="1003" alt="Screen Shot 2019-04-15 at 9 49 00 AM" src="https://user-images.githubusercontent.com/4001122/56139190-6823f280-5f66-11e9-9a48-87499ef64c3c.png">

**Browser**
<img width="1098" alt="Screen Shot 2019-04-15 at 10 09 31 AM" src="https://user-images.githubusercontent.com/4001122/56139344-acaf8e00-5f66-11e9-9a67-c3a0b6001ece.png">

**CURL output**
```
curl -I http://localhost:80
HTTP/1.1 200 OK
Date: Mon, 15 Apr 2019 14:07:01 GMT
X-Content-Type-Options: nosniff
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-cache,no-store,must-revalidate
X-Hudson-Theme: default
Referrer-Policy: same-origin
Content-Type: text/html;charset=utf-8
Set-Cookie: JSESSIONID.7fa118ae=node01xw1mhpwm6cw1ety9eeap44ne3.node0;Path=/;HttpOnly
X-Hudson: 1.395
X-Jenkins: 2.173
X-Jenkins-Session: fbb9e50e
X-Hudson-CLI-Port: 50000
X-Jenkins-CLI-Port: 50000
X-Jenkins-CLI2-Port: 50000
X-Frame-Options: sameorigin
X-Instance-Identity: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkK3X1yxjKHjDzLB4g+3uZZomuyHpQrTKOQR1bn/MfLskU1SzQpbhwIQzh46udaK6BdpINIZO5zZdPL5j5yQ3vfry8MW5JYqHMtq0G4JHCRA6g4W/jFlAwpZ6QU0m88cHSsHjcvFR6FD7A2cY0cwTh5/jfc1xn8u9XJFQEw9fifTvKfzBRfbILPJDHlysx9jJqEhgdjwE0UD9tJF3Bt7sllL+Po60y+QKPw0yXktPex4HCoMXIxmq+7b0HBrW1O7iosj9hM3oQHnHLimn8t4V/0iX3rVJiuiAsdoEnZI9aWEUXuNMjncinOV61QNQWpr/L/OYMCLzR+Ab5eo6rmTUYwIDAQAB
Content-Length: 13751
Server: Jetty(9.4.z-SNAPSHOT)
```

**Comment by dave-hagedorn** [comment]
Hi there - I think this shows up when there is no Jenkins user (anonymous access is enabled).  I should have a fix shortly.  

In the meantime, I would suggest trying with a Jenkins user and password, to see if that fixes the issue.  Apologies for any inconvenience.

Thanks.

**Comment by dave-hagedorn** [comment]
Just released 1.1.0 which should fix this.  Thanks for the detailed bug report!

**Comment by nickpetrovic** [comment]
Confirmed that it works. Thanks for the quick turn around!

**Comment by tndhagedorn** [comment]
Great - glad to hear it's working for you.

**Comment by Drugoy** [comment]
@dave-hagedorn I'm using 1.1.0 and I have a similar problem:
`TypeError: Cannot read property '0' of undefined`

**Comment by dave-hagedorn** [comment]
Hi @Drugoy,

Do you have logs for this issue - "TypeError: Cannot read property '0' of
undefined".

Happy to take a look - thanks!

Dave

**Comment by hari2m** [comment]
I have the same issue with the user included. 

> TypeError: Cannot read property 'definition' of undefined

 When I try with the URL having a "/" at the end is trying to connect and then not do anything. But when I remove the "/" at the end of the URL I get the Type Error. I tried removing the parameters of the settings but still, it tries to pass #undefined as a parameter for the job.

**Comment by dave-hagedorn** [comment]
> I have the same issue with the user included.
> 
> > TypeError: Cannot read property 'definition' of undefined
> 
> When I try with the URL having a "/" at the end is trying to connect and then not do anything. But when I remove the "/" at the end of the URL I get the Type Error. I tried removing the parameters of the settings but still, it tries to pass #undefined as a parameter for the job.

Hi @hari2m,

I opened a ticket - #9 - for your comment.  Can you please provide more details there?  Thanks!
