### ISSUE TITLE
Pass Environment variable to job

### ISSUE THREAD

**Issue by Roman-Bober** [dave-hagedorn/jenkins-runner#19]
Hi,
I use gitlab integrations with jenkins 
So when job runs, heavily using the environment variables sent by gitlab to jenkins job such as:
 gitlabSourceRepoName
 gitlabBranch

Is it possible to set those variables synthetically (like int the "parameters" of job config)?

Thank you,
Roman

**Comment by dave-hagedorn** [comment]
Hi @Roman-Bober - I think I have something that will work, and should make the next release.

It requires a user to have the [envinject](https://plugins.jenkins.io/envinject/) plugin installed.  If detected, the plugin will leverage that to override environment variables before running the job.
