### ISSUE TITLE
strictSSL configuration?

### ISSUE THREAD

**Issue by atiniir** [dave-hagedorn/jenkins-runner#2]
hey just curious if there is any way to set strictSSL=false?

**Comment by dave-hagedorn** [comment]
Hi there - not familiar with this setting - do you know where would it be set?  Thanks.

**Comment by atiniir** [comment]
I'm curious about this as I'm getting this error when I try to run a job:

[2019-05-07 11:15:46.764] [Jenkins] [info] Fetching remote XML config for job kris-tester @https://myjenkins
[2019-05-07 11:15:47.357] [Jenkins] [error] Error starting job kris-tester #undefined @myjenkins}: Error: jenkins: job.config: unable to verify the first certificate

I get the same error from the https://marketplace.visualstudio.com/items?itemName=janjoerke.jenkins-pipeline-linter-connector plugin unless i set the option "Jenkins > Pipeline > Linter > Connector: Strictssl 

Looking at the source for that plugin at https://github.com/janjoerke/vscode-jenkins-pipeline-linter-connector/blob/71f8178f13660310cdfac7051f5b9ba34c003f49/src/extension.ts it looks like in the validateRequest fn they are using it for a similarly named flag to reading a filestream... 
```
<snip>
        let filestream = fs.createReadStream(path);
        const chunks: any = [];
        filestream.on('data', (chunk: any) => {
            chunks.push(chunk.toString());
        });
        filestream.on('end', () => {
            let options: any = {
                method: 'POST',
                url: url,
                strictSSL: strictssl,
                formData: {
                    'jenkinsfile': chunks.join()
                }
            };
<snip>
```

**Comment by atiniir** [comment]
I looked at the jenkins package you are using but I didn't notice a straightforward way to set this when init'ing the jenkins instance.

**Comment by dave-hagedorn** [comment]
Hi there - just curious - are you using a self-signed or otherwise unverified SSL cert?

I can reproduce something similar (but not quite the same) by setting up a local Jenkins instance with a self-signed cert, and connecting over SSL

**Comment by dave-hagedorn** [comment]
Hello - I just release a new version - this adds the `rejectUnauthorizedCert` option to a host config.  

I would suggest you with this set to `false`.  This allowed me to use a self-signed SSL cert, which was previously failing.

**Comment by dave-hagedorn** [comment]
FYI - make sure you get the 1.2.2 version - 1.2.1 had a minor bug.

**Comment by atiniir** [comment]
that works brilliantly! thank you so much for addressing this. apologies it took me so long to test and confirm.

**Comment by dave-hagedorn** [comment]
NP - glad to hear it's working!  Thanks for following up.
